version: 2


sources:
  - name: tpch
    database: raw
    schema: tpch_sf001
    tables:
      - name: orders
        description: main order tracking table
        freshness: # make this a warning as this is static data
          warn_after: {count: 6, period: hour}
          # error_after: {count: 12, period: hour}
        loaded_at_field: o_orderdate::timestamp
        
        columns:
          - name: o_orderkey
            description: SF*1,500,000 are sparsely populated
            tests: 
              - unique
              - not_null
      
      - name: customer
        description: main customer table
        columns:
          - name: c_custkey
            description: unique customer key
            tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn

      - name: lineitem
        description: main lineitem table
        columns:
          - name: l_orderkey
            description: Foreign Key to O_ORDERKEY
            tests:
              - relationships:
                  to: source('tpch', 'orders')
                  field: o_orderkey

#for the example with multiple sources depending on the environment
  - name: tpch_qa
    description: Welcome to the dbt Labs demo dbt project! We use the [TPCH dataset](https://docs.snowflake.com/en/user-guide/sample-data-tpch.html) to create a sample project to emulate what a production project might look like!
    database: raw
    schema: tpch_sf001
    tables:
      - name: order_items
      