version: 2

sources:
  - name: jaffle_shop
    tables:
      - name: raw_customers

models:
  - name: stg_customers
    tests:
      - dbt_datamocktool.unit_test:
          input_mapping:
            ref('raw_customers'): ref('dmt__raw_customers_1') # this is a seed
          expected_output: ref('dmt__expected_stg_customers_1') # this is also a seed
          depends_on:
            - ref('raw_customers')